### PR TITLE
Fix Debug ASSERT fails

### PR DESCRIPTION
**Pull request by docsteer**
Fixes a couple of debugging assert fails in the ItemModel for source discovery.

### CODE REVIEW

**Comment by marcusbirkin** [comment]
I'm not sure ResetModel() is best for this, RemoveRows() was definitely wrong!
#a560b5cceb89bd0e350538a9ae40226e167ece81 utilises the commented out code, which was InsertRow()

**Comment by docsteer** [comment]
ResetModel() was definitely the lazy solution. Wouldn't the proper one really be to use beginMoveRows/endMoveRows?

**Comment by marcusbirkin** [comment]
It's definitely inserting a new row, and the qsort means that it might move a row.
What I'll do is emit an insert, then sort, then emit a move (if the sort sorts something).

**Comment by docsteer** [comment]
@marcusbirkin I think I came up with a better/more Qt-like solution, a QSortFilterProxyModel between the source discovery model and the UI. That lays the groundwork for additional things we might want to add like making the list searchable. Take a look and let me know what you think, then I'll merge and do a build

**Pull request merged**
