### PR TITLE
Don't disable level tabs in transmit window

### PR DESCRIPTION
**Pull request by marcusbirkin**
Addresses #145

### CODE REVIEW

**Comment by docsteer** [comment]
Also something funky happens with sliders and slot counts <24 in this pull request.. if I set it to 12, somehow the faders can only start at 12, and the numbering gets all funky..

**Comment by marcusbirkin** [comment]
This should work better (incorporating #162)

**Comment by docsteer** [comment]
Oops, found one more now. Sliders are disabled but I can still enter values >12 and crash with the keypad

**Comment by marcusbirkin** [comment]
Entering levels via the keypad was left intentionally (and reflected by disabled faders).
What steps crash it?

**Comment by docsteer** [comment]
Tested with the appveyor build (on win10 64bit), just running the program, click the transmitter button, set slot count to 12, then start entering values on the keypad, crashes. I'll try and fire up a debugger to narrow it down.

**Comment by docsteer** [comment]
Found it, pointer arithmetic kills us again. The problem is that when the buffer is initialized in CStreamServer::createUniverse, we are using the user defined number of slots. However, when levels are set using the keypad, we are still calling sACNSentUniverse::setLevel() with the full 0-511 range. Should probably update the ASSERT statements to use the length to make this easier to find.

**Comment by marcusbirkin** [comment]
Interestingly that doesn't explode on my Linux desktop.
I've not added assert, but if statements with returns, reason being I don't want to loose information from the transmit window "programmer". This way you can limit your slot count, set levels in addresses above the limit, and then increase the slot count without losing level info.

**Comment by docsteer** [comment]
Much better! At some point we should probably do some checking using valgrind or something. You get a pretty impressive list of safety warnings running the project through the Qt creator static analysis tools at the moment.

**Pull request merged**
